# Generated by Django 3.2 on 2021-04-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_alter_driver_have_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_bid', models.CharField(max_length=20, verbose_name='Код заявки')),
                ('time_start', models.DateTimeField(auto_now=True, verbose_name='Время начала поездки')),
                ('time_end', models.CharField(max_length=20, verbose_name='Время окончания поездки')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.driver')),
            ],
            options={
                'verbose_name': ('Обслуживание заявки',),
                'verbose_name_plural': 'Обслуживание заявок',
            },
        ),
        migrations.CreateModel(
            name='TaximeterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_parameter', models.CharField(max_length=20, verbose_name='Код парамерта')),
                ('code_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rate.servicebid')),
            ],
            options={
                'verbose_name': ('Значение таксометра',),
                'verbose_name_plural': 'Значения таксометров',
            },
        ),
        migrations.CreateModel(
            name='TaximeterTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_unit', models.IntegerField(max_length=20, verbose_name='Еденица измерения параметра')),
                ('price', models.IntegerField(max_length=20, verbose_name='Цена')),
                ('code_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rate.taximetervalue')),
            ],
            options={
                'verbose_name': ('Тариф таксометра',),
                'verbose_name_plural': 'Тарифы таксометров',
            },
        ),
    ]
