# Generated by Django 3.2 on 2021-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taximetertarif',
            name='car_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Категория машины'),
        ),
        migrations.AlterField(
            model_name='taximetertarif',
            name='parameter_unit',
            field=models.IntegerField(verbose_name='Еденица измерения параметра'),
        ),
        migrations.AlterField(
            model_name='taximetertarif',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
