# Generated by Django 3.2 on 2021-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rate', '0002_auto_20210415_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taximetertarif',
            name='car_category',
        ),
        migrations.AddField(
            model_name='taximetertarif',
            name='Tarif',
            field=models.CharField(blank=True, choices=[('Стандарт', 'Стандарт'), ('Комфорт', 'Комфорт'), ('Бизнес', 'Бизнес')], default='Стандарт', max_length=10),
        ),
    ]
