# Generated by Django 3.2 on 2021-04-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Марка машины')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет машины')),
                ('state_number', models.CharField(max_length=9, verbose_name='Государсвенный номерной знак')),
                ('status', models.CharField(blank=True, choices=[('r', 'repairs'), ('w', 'work')], default='w', max_length=1)),
            ],
            options={
                'verbose_name': ('Машина',),
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(max_length=20, verbose_name='Дата рождения')),
                ('work_experience', models.IntegerField(verbose_name='Стаж работы')),
                ('status', models.CharField(blank=True, choices=[('n', 'not on line'), ('y', 'on the line')], default='y', max_length=1)),
                ('callsign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'verbose_name': ('Водитель',),
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='carBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Марка машины')),
                ('brand_сode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'verbose_name': ('Марка машины',),
                'verbose_name_plural': 'Марки машин',
            },
        ),
    ]
