# Generated by Django 3.2 on 2021-04-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='have_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='callsign',
            field=models.CharField(max_length=20, verbose_name='Позывной'),
        ),
    ]
