# Generated by Django 3.2 on 2021-04-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210415_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='have_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
