# Generated by Django 3.2 on 2021-04-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_driver_have_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': ('Модель машины',), 'verbose_name_plural': 'Модели машин'},
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carbrand'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(max_length=20, verbose_name='Модель машины'),
        ),
    ]
