# Generated by Django 3.2 on 2021-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_carbrand_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=20, verbose_name='Марка машины'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Модель машины'),
        ),
    ]
