# Generated by Django 3.2 on 2021-04-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': ('Локация',), 'verbose_name_plural': 'Локации'},
        ),
        migrations.AddField(
            model_name='location',
            name='name_area',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_area',
            field=models.CharField(max_length=20, verbose_name='Название района'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name_street',
            field=models.CharField(max_length=20, verbose_name='Название улицы'),
        ),
    ]
